travis:
  secure:
    BINSTAR_TOKEN: iKT4OOOz9fR7z89mI160lvLyH3+aHOD6M+dyD74+F6CV6OUefTNbTosv5waewBdEy7UN1VQT8wCrqxgXBsVcZoKMPubrySRaKlsgWZApAoTgLAQ2nMYgz2nI/ctAPmv3sxK/9Wab5gi3hSky7l1QgG+SgqFCq979AjrPCC7IilQrojH0eXTE1FLoKwkfjrHfbffE/Ib/J/QNOMYgL9SIo1w1GV8mLm5KykZISH6aI8ih8tzuPvjIavljDOhx6eoENJw9ZrE1QuqfoRbM8VBggXMFS5F5Th4MjLFdtdbpAaK8ZSQHLJnRzWG3fcurA0f1vBqNHsWdYuXCQ9cCmjs8ZKm2D0CAMctni+IT/U78og1iIHPedKpmQp/IBCfe/u9zdfqcqhwlOAqp+ITSblaJ7+XRknq7OmwhK2cKNQzxx7TrGBogU+G9OCV2xLVSpvDN4P04912hEkaAI4dIW/GsAVx+g1wG/77XrSBTa8lqTiPWxrIQOTt3c82+yjxa9kl9cLHv9e0g+QM6OoQeliGwiy4yvCG0BLbbr2XfJWELJjuOy5uFyV8UNtkttuMYMx5ZU+OQGKaDkTYby0+Vrwt/nnqppBKE2EQlwLLQmjxHcyezZ3BNj1D9yNf690J0fd2YuNC9Zb/iKFYJXl9ZYRnJXpMfhmHljWVM3nvkV9q+H0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
